[package]
name = "code-engine-core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
mlua = { version = "0.9", features = ["lua54", "serialize"] }
clap = { version = "4", features = ["derive"] }
