# Global settings for the AI bot
start_url: "https://example.com"
goals:
  - Collect data from the web
  - Plan actions based on the data
  - Generate or modify code
testing_enabled: true
log_thoughts: true
auto_evaluate: false
enable_recursive_planning: false
allow_self_rewrites: false
plugins:
  enabled:
    - github_issues
    - rss_reader
  github_issues:
    repo: "octocat/Hello-World"
  rss_reader:
    url: "https://hnrss.org/frontpage"
