name: Run Python and Node tests

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run Python tests
        run: pytest apps/bot/tests

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install frontend dependencies
        run: |
          if [ -f apps/web/package.json ]; then
            cd apps/web && npm ci
          fi

      - name: Run frontend tests
        run: |
          if [ -f apps/web/package.json ] && grep -q "\"test\"" apps/web/package.json; then
            cd apps/web && npm test
          else
            echo "No frontend tests defined"
          fi

      - name: Install backend dependencies
        run: |
          if [ -f apps/backend/express/package.json ]; then
            cd apps/backend/express && npm ci
          fi

      - name: Run backend tests
        run: |
          if [ -f apps/backend/express/package.json ] && grep -q "\"test\"" apps/backend/express/package.json; then
            cd apps/backend/express && npm test
          else
            echo "No backend tests defined"
          fi
